#!/bin/bash
#PBS -N test_4process_4pair
#PBS -l select=1:node_type=hsw:mpiprocs=4
#PBS -l walltime=00:05:00             
  
# Change to the direcotry that the job was submitted from
cd $PBS_O_WORKDIR


# Launch the parallel mpi application (compiled with intel mpi) to the allocated compute nodes
module load python/3
module load mpi/openmpi/4.0.5-intel-19.1.0
mpirun -np 4 ./python_code/frostdates > my_output_file 2>&1
python joining_files.py
