#!/bin/bash
#PBS -N test_4process_4pair
#PBS -l select=1:node_type=rome:mpiprocs=4
#PBS -l walltime=00:30:00
#PBS -q euxdat


# Change to the direcotry that the job was submitted from
cd $PBS_O_WORKDIR


# Launch the parallel mpi application (compiled with intel mpi) to the allocated compute nodes
module load python/3
rm -Rf export/
mkdir export
time mpirun -np 4 ./python_code/frostdates > my_output_file 2>&1
sh delete_small_files.sh
python joining_files.py
